import { writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import path from "node:path";
import { SERVICE_NAME } from "@rekha/shared";

const require = createRequire(import.meta.url);

/** Resolves the absolute path to the server entrypoint PM2 should run. */
export function resolveServerEntry(): string {
  // Published bundle: cli.js and server.js sit side by side in dist/.
  const sibling = path.join(path.dirname(fileURLToPath(import.meta.url)), "server.js");
  if (existsSync(sibling)) return sibling;
  // Dev/workspace fallback: resolve the @rekha/server package main.
  const pkg = "@rekha/server";
  return require.resolve(pkg);
}

export function writeEcosystem(file: string, home: string): void {
  const serverEntry = resolveServerEntry();
  const config = `// Generated by "rekha install" — do not edit by hand.
module.exports = {
  apps: [
    {
      name: "${SERVICE_NAME}",
      script: ${JSON.stringify(serverEntry)},
      cwd: ${JSON.stringify(home)},
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      env: {
        NODE_ENV: "production",
        REKHA_HOME: ${JSON.stringify(home)}
      }
    }
  ]
};
`;
  writeFileSync(file, config, { mode: 0o644 });
}
